"""Proxy DHCP server management via dnsmasq."""

import json
import logging
import os
import subprocess
import time
from pathlib import Path

from pydantic import BaseModel

logger = logging.getLogger(__name__)

SETTINGS_FILE = Path("/srv/dhcp/proxy-dhcp.json")
PID_FILE = Path("/tmp/dnsmasq-proxy.pid")
CONF_FILE = Path("/tmp/dnsmasq-proxy.conf")


class ProxyDHCPSettings(BaseModel):
    """Settings for the Proxy DHCP dnsmasq instance."""

    enabled: bool = False
    server_ip: str = "192.168.1.1"
    subnet: str = ""
    http_port: int = 9021
    support_bios: bool = True
    support_uefi: bool = True


class ProxyDHCPManager:
    """Manages a dnsmasq Proxy DHCP process."""

    def get_pid(self) -> int | None:
        """Return PID from the pid file, or None if not present / not a number."""
        try:
            return int(PID_FILE.read_text().strip())
        except (FileNotFoundError, ValueError):
            return None

    def is_running(self) -> bool:
        """Return True if the dnsmasq process recorded in the pid file is alive."""
        pid = self.get_pid()
        if pid is None:
            return False
        return Path(f"/proc/{pid}").exists()

    def _derive_subnet(self, ip: str) -> str:
        """Return the /24 network address for *ip* (last octet → 0)."""
        parts = ip.rsplit(".", 1)
        if len(parts) == 2:
            return f"{parts[0]}.0"
        return ip

    def generate_conf(self, settings: ProxyDHCPSettings) -> str:
        """Build a dnsmasq proxy-DHCP config string from *settings*."""
        subnet = settings.subnet or self._derive_subnet(settings.server_ip)
        ip = settings.server_ip

        lines = [
            "# Generated by iPXE Station — do not edit manually",
            "port=0",
            "log-dhcp",
            "",
            f"dhcp-range={subnet},proxy",
            "",
            "# Tag iPXE clients (option 175 present)",
            "dhcp-match=set:ipxe,175",
            "",
            "# pxe-service sends both OFFER (type 2) and ACK (type 5) in proxy mode.",
            "# dhcp-boot sends only OFFER — undionly.kpxe ignores it.",
            "# So pxe-service is required for both iPXE and non-iPXE clients.",
        ]

        if settings.support_bios:
            # Non-iPXE BIOS: chainload undionly.kpxe to get full iPXE stack
            lines.append(f'pxe-service=tag:!ipxe,x86PC,"Network Boot (BIOS)",undionly.kpxe,{ip}')
            # iPXE BIOS: load autoexec.ipxe directly via TFTP (ACK delivers the filename)
            lines.append(f'pxe-service=tag:ipxe,x86PC,"iPXE Boot",autoexec.ipxe,{ip}')
        if settings.support_uefi:
            lines.append(f'pxe-service=x86-64_EFI,"Network Boot (UEFI)",ipxe.efi,{ip}')
            lines.append(f'pxe-service=BC_EFI,"Network Boot (UEFI32)",ipxe.efi,{ip}')

        return "\n".join(lines) + "\n"

    def start(self, settings: ProxyDHCPSettings) -> dict:
        """Write config, launch dnsmasq, and verify it started."""
        if self.is_running():
            self.stop()

        CONF_FILE.write_text(self.generate_conf(settings))

        result = subprocess.run(
            [
                "dnsmasq",
                f"--conf-file={CONF_FILE}",
                f"--pid-file={PID_FILE}",
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )

        if result.returncode != 0:
            error = result.stderr.strip() or "dnsmasq exited with non-zero status"
            logger.error("dnsmasq failed to start: %s", error)
            return {"success": False, "error": error}

        # Give dnsmasq a moment to write its pid file
        time.sleep(0.5)

        if not self.is_running():
            return {"success": False, "error": "dnsmasq did not stay running after start"}

        pid = self.get_pid()
        logger.info("Proxy DHCP started — pid %s", pid)
        return {"success": True, "pid": pid}

    def stop(self) -> dict:
        """Send SIGTERM to the dnsmasq process and clean up."""
        pid = self.get_pid()
        if pid is None:
            return {"success": True, "message": "Not running"}

        try:
            os.kill(pid, 15)  # SIGTERM
            time.sleep(0.3)
        except ProcessLookupError:
            pass  # Already gone
        except PermissionError as exc:
            return {"success": False, "error": str(exc)}

        try:
            PID_FILE.unlink(missing_ok=True)
        except OSError:
            pass

        logger.info("Proxy DHCP stopped (was pid %s)", pid)
        return {"success": True, "message": f"Stopped pid {pid}"}

    def load_settings(self) -> ProxyDHCPSettings:
        """Load settings from SETTINGS_FILE, falling back to defaults.

        If server_ip is blank or still the placeholder default, substitute the
        real PXE server IP from the application config.
        """
        try:
            data = json.loads(SETTINGS_FILE.read_text())
            s = ProxyDHCPSettings(**data)
        except (FileNotFoundError, json.JSONDecodeError, TypeError):
            s = ProxyDHCPSettings()

        if not s.server_ip or s.server_ip == "192.168.1.1":
            from app.backend.config import settings as _cfg

            s = s.model_copy(update={"server_ip": _cfg.pxe_server_ip})

        return s

    def save_settings(self, settings: ProxyDHCPSettings) -> None:
        """Persist *settings* to SETTINGS_FILE."""
        SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
        SETTINGS_FILE.write_text(settings.model_dump_json(indent=2))

    def get_status(self) -> dict:
        """Return current running state and persisted settings."""
        running = self.is_running()
        return {
            "running": running,
            "pid": self.get_pid() if running else None,
            "settings": self.load_settings().model_dump(),
        }
