"""Proxy DHCP server management via dnsmasq."""

import json
import logging
import os
import subprocess
import time
from pathlib import Path

from pydantic import BaseModel

logger = logging.getLogger(__name__)

SETTINGS_FILE = Path("/srv/dhcp/proxy-dhcp.json")
PID_FILE = Path("/tmp/dnsmasq-proxy.pid")
CONF_FILE = Path("/tmp/dnsmasq-proxy.conf")


class ProxyDHCPSettings(BaseModel):
    """Settings for the Proxy DHCP dnsmasq instance."""

    enabled: bool = False
    server_ip: str = "192.168.1.1"
    subnet: str = ""
    http_port: int = 9021
    support_bios: bool = True
    support_uefi: bool = True


class ProxyDHCPManager:
    """Manages a dnsmasq Proxy DHCP process."""

    def get_pid(self) -> int | None:
        """Return PID from the pid file, or None if not present / not a number."""
        try:
            return int(PID_FILE.read_text().strip())
        except (FileNotFoundError, ValueError):
            return None

    def is_running(self) -> bool:
        """Return True if the dnsmasq process recorded in the pid file is alive."""
        pid = self.get_pid()
        if pid is None:
            return False
        return Path(f"/proc/{pid}").exists()

    def _derive_subnet(self, ip: str) -> str:
        """Return the /24 network address for *ip* (last octet → 0)."""
        parts = ip.rsplit(".", 1)
        if len(parts) == 2:
            return f"{parts[0]}.0"
        return ip

    def generate_conf(self, settings: ProxyDHCPSettings) -> str:
        """Build a dnsmasq proxy-DHCP config string from *settings*."""
        subnet = settings.subnet or self._derive_subnet(settings.server_ip)
        lines = [
            "# Generated by iPXE Station — do not edit manually",
            "port=0",
            "log-dhcp",
            "",
            f"dhcp-range={subnet},proxy",
            "dhcp-no-override",
            "",
            "# Detect iPXE (already chainloaded — option 175 present)",
            "dhcp-match=set:ipxe,175",
            "",
            "# Detect client architecture",
        ]

        if settings.support_bios:
            lines.append("dhcp-match=set:bios,option:client-arch,0")
        if settings.support_uefi:
            lines.append("dhcp-match=set:efi64,option:client-arch,7")
            lines.append("dhcp-match=set:efi32,option:client-arch,6")

        lines.append("")
        lines.append("# iPXE clients → send boot script URL directly")
        lines.append(
            f"dhcp-boot=tag:ipxe,http://{settings.server_ip}:{settings.http_port}/boot.ipxe"
        )
        lines.append("")

        if settings.support_bios:
            lines.append("# BIOS (not iPXE) → chainload undionly.kpxe via TFTP")
            lines.append(f"dhcp-boot=tag:bios,tag:!ipxe,undionly.kpxe,,{settings.server_ip}")

        if settings.support_uefi:
            lines.append("# UEFI (not iPXE) → chainload ipxe.efi via TFTP")
            lines.append(f"dhcp-boot=tag:efi64,tag:!ipxe,ipxe.efi,,{settings.server_ip}")
            lines.append(f"dhcp-boot=tag:efi32,tag:!ipxe,ipxe.efi,,{settings.server_ip}")

        return "\n".join(lines) + "\n"

    def start(self, settings: ProxyDHCPSettings) -> dict:
        """Write config, launch dnsmasq, and verify it started."""
        if self.is_running():
            self.stop()

        CONF_FILE.write_text(self.generate_conf(settings))

        result = subprocess.run(
            [
                "dnsmasq",
                f"--conf-file={CONF_FILE}",
                f"--pid-file={PID_FILE}",
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )

        if result.returncode != 0:
            error = result.stderr.strip() or "dnsmasq exited with non-zero status"
            logger.error("dnsmasq failed to start: %s", error)
            return {"success": False, "error": error}

        # Give dnsmasq a moment to write its pid file
        time.sleep(0.5)

        if not self.is_running():
            return {"success": False, "error": "dnsmasq did not stay running after start"}

        pid = self.get_pid()
        logger.info("Proxy DHCP started — pid %s", pid)
        return {"success": True, "pid": pid}

    def stop(self) -> dict:
        """Send SIGTERM to the dnsmasq process and clean up."""
        pid = self.get_pid()
        if pid is None:
            return {"success": True, "message": "Not running"}

        try:
            os.kill(pid, 15)  # SIGTERM
            time.sleep(0.3)
        except ProcessLookupError:
            pass  # Already gone
        except PermissionError as exc:
            return {"success": False, "error": str(exc)}

        try:
            PID_FILE.unlink(missing_ok=True)
        except OSError:
            pass

        logger.info("Proxy DHCP stopped (was pid %s)", pid)
        return {"success": True, "message": f"Stopped pid {pid}"}

    def load_settings(self) -> ProxyDHCPSettings:
        """Load settings from SETTINGS_FILE, falling back to defaults."""
        try:
            data = json.loads(SETTINGS_FILE.read_text())
            return ProxyDHCPSettings(**data)
        except (FileNotFoundError, json.JSONDecodeError, TypeError):
            return ProxyDHCPSettings()

    def save_settings(self, settings: ProxyDHCPSettings) -> None:
        """Persist *settings* to SETTINGS_FILE."""
        SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
        SETTINGS_FILE.write_text(settings.model_dump_json(indent=2))

    def get_status(self) -> dict:
        """Return current running state and persisted settings."""
        running = self.is_running()
        return {
            "running": running,
            "pid": self.get_pid() if running else None,
            "settings": self.load_settings().model_dump(),
        }
