from app.backend.ipxe_manager import iPXEEntry, iPXEGenerator, iPXEMenu


def test_ipxe_generator_snapshot():
    menu = iPXEMenu(
        title="Test Menu",
        timeout=5000,
        default_entry="ubuntu",
        server_ip="10.0.0.1",
        http_port=8080,
        entries=[
            iPXEEntry(
                name="ubuntu",
                title="Ubuntu Netboot",
                kernel="ubuntu/vmlinuz",
                initrd="ubuntu/initrd",
                cmdline="ip=dhcp",
                boot_mode="netboot",
                entry_type="boot",
            )
        ],
    )

    script = iPXEGenerator.generate_ipxe_script(menu)

    expected = """#!ipxe

# iPXE Boot Menu - Enhanced Multi-Mode Support
# Generated by PXE Boot Station

:start
menu Test Menu
item --gap -- -------------------------------
item ubuntu [NET] Ubuntu Netboot
item --gap --
item shell [SHELL]  Drop to iPXE shell
item reboot [REBOOT] Reboot computer
item exit [EXIT] Exit to BIOS
choose --default ubuntu --timeout 5000 target && goto ${target}

:ubuntu
echo Booting Ubuntu Netboot...
kernel http://10.0.0.1:8080/http/ubuntu/vmlinuz ip=dhcp
initrd http://10.0.0.1:8080/http/ubuntu/initrd
boot
goto start

:shell
echo Dropping to iPXE shell...
shell

:reboot
echo Rebooting in 3 seconds...
sleep 3
reboot

:exit
echo Exiting to BIOS...
exit

:error
echo Boot failed, returning to menu...
sleep 3
goto start
"""

    assert script.strip() == expected.strip()
