from app.backend.ipxe_manager import iPXEEntry, iPXEGenerator, iPXEMenu


def test_ipxe_generator_snapshot():
    menu = iPXEMenu(
        title="Test Menu",
        timeout=5000,
        default_entry="ubuntu",
        server_ip="10.0.0.1",
        http_port=8080,
        entries=[
            iPXEEntry(
                name="ubuntu",
                title="Ubuntu Netboot",
                kernel="ubuntu/vmlinuz",
                initrd="ubuntu/initrd",
                cmdline="ip=dhcp",
                boot_mode="netboot",
                entry_type="boot",
            )
        ],
    )

    script = iPXEGenerator.generate_ipxe_script(menu)

    expected = """#!ipxe

# iPXE Boot Menu - Enhanced Multi-Mode Support
# Generated by PXE Boot Station

# Report what this machine is (brand, model, serial, BIOS, NIC) to the monitoring log
imgfetch --name client-info http://10.0.0.1:8080/client-info?mac=${net0/mac}&uuid=${uuid}&manufacturer=${manufacturer:uristring}&product=${product:uristring}&sku=${smbios/1.25.0:uristring}&family=${smbios/1.26.0:uristring}&serial=${serial:uristring}&asset=${asset:uristring}&bios_version=${smbios/0.5.0:uristring}&bios_date=${smbios/0.8.0:uristring}&platform=${platform}&arch=${buildarch}&busid=${net0/busid:hexhyp}&chip=${net0/chip:uristring}&ipxe=${version:uristring} || echo Client info report skipped
imgfree client-info ||

:start
menu Test Menu
item --gap -- -------------------------------
item ubuntu [NET] Ubuntu Netboot
item --gap --
item shell [SHELL]  Drop to iPXE shell
item reboot [REBOOT] Reboot computer
item exit [EXIT] Exit to BIOS
choose --default ubuntu --timeout 5000 target && goto ${target}

:ubuntu
echo Booting Ubuntu Netboot...
kernel http://10.0.0.1:8080/http/ubuntu/vmlinuz ip=dhcp
initrd http://10.0.0.1:8080/http/ubuntu/initrd
boot
goto start

:shell
echo Dropping to iPXE shell...
shell

:reboot
echo Rebooting in 3 seconds...
sleep 3
reboot

:exit
echo Exiting to BIOS...
exit

:error
echo Boot failed, returning to menu...
sleep 3
goto start
"""  # noqa: E501

    assert script.strip() == expected.strip()


def test_hiren_winpe_wimboot_flow_uses_multi_initrd():
    menu = iPXEMenu(
        title="Test Menu",
        timeout=5000,
        default_entry="hiren",
        server_ip="10.0.0.1",
        http_port=8080,
        entries=[
            iPXEEntry(
                name="hiren",
                title="Hiren WinPE",
                kernel="wimboot",
                initrd="hiren-1.0.8/bootmgr",
                boot_mode="rescue",
                entry_type="boot",
                hiren_winpe_ready=True,
                hiren_bootmgr="hiren-1.0.8/bootmgr",
                hiren_bcd="hiren-1.0.8/Boot/BCD",
                hiren_boot_sdi="hiren-1.0.8/Boot/boot.sdi",
                hiren_boot_wim="hiren-1.0.8/sources/boot.wim",
            )
        ],
    )

    script = iPXEGenerator.generate_ipxe_script(menu)

    assert "kernel http://10.0.0.1:8080/http/wimboot" in script
    assert "initrd http://10.0.0.1:8080/http/hiren-1.0.8/bootmgr bootmgr" in script
    assert "initrd http://10.0.0.1:8080/http/hiren-1.0.8/Boot/BCD BCD" in script
    assert "initrd http://10.0.0.1:8080/http/hiren-1.0.8/Boot/boot.sdi boot.sdi" in script
    assert "initrd http://10.0.0.1:8080/http/hiren-1.0.8/sources/boot.wim boot.wim" in script


def test_hiren_winpe_minimal_flow_uses_boot_wim():
    menu = iPXEMenu(
        title="Test Menu",
        timeout=5000,
        default_entry="hiren",
        server_ip="10.0.0.1",
        http_port=8080,
        entries=[
            iPXEEntry(
                name="hiren",
                title="Hiren WinPE Minimal",
                kernel="wimboot",
                initrd="hiren-1.0.8/sources/boot.wim",
                boot_mode="rescue",
                entry_type="boot",
                hiren_winpe_ready=True,
                hiren_boot_wim="hiren-1.0.8/sources/boot.wim",
            )
        ],
    )

    script = iPXEGenerator.generate_ipxe_script(menu)

    assert "kernel http://10.0.0.1:8080/http/wimboot" in script
    assert "bootmgr bootmgr" not in script
    assert " Boot/BCD BCD" not in script
    assert "boot.sdi boot.sdi" not in script
    assert "initrd http://10.0.0.1:8080/http/hiren-1.0.8/sources/boot.wim boot.wim" in script


def test_windows_pe_wimboot_multi_initrd():
    """windows_pe scenario: initrd field split into per-file initrd lines with filename aliases."""
    menu = iPXEMenu(
        title="Test Menu",
        timeout=5000,
        default_entry="winpe",
        server_ip="10.0.0.1",
        http_port=8080,
        entries=[
            iPXEEntry(
                name="winpe",
                title="Windows PE",
                kernel="wimboot",
                initrd="winpe/Boot/BCD winpe/Boot/boot.sdi winpe/sources/boot.wim",
                boot_mode="custom",
                entry_type="boot",
            )
        ],
    )

    script = iPXEGenerator.generate_ipxe_script(menu)

    assert "kernel http://10.0.0.1:8080/http/wimboot" in script
    assert "initrd http://10.0.0.1:8080/http/winpe/Boot/BCD BCD" in script
    assert "initrd http://10.0.0.1:8080/http/winpe/Boot/boot.sdi boot.sdi" in script
    assert "initrd http://10.0.0.1:8080/http/winpe/sources/boot.wim boot.wim" in script
    # Single-line initrd must NOT be used
    assert "initrd http://10.0.0.1:8080/http/winpe/Boot/BCD winpe/Boot/boot.sdi" not in script


def test_legacy_iso_memdisk_flow_uses_iso_raw_cmdline():
    menu = iPXEMenu(
        title="Test Menu",
        timeout=5000,
        default_entry="gparted",
        server_ip="10.0.0.1",
        http_port=8080,
        entries=[
            iPXEEntry(
                name="gparted",
                title="GParted Live",
                kernel="memdisk",
                initrd="gparted-live-1.7.0.iso",
                cmdline="iso raw",
                boot_mode="rescue",
                entry_type="boot",
            )
        ],
    )

    script = iPXEGenerator.generate_ipxe_script(menu)

    assert "kernel http://10.0.0.1:8080/http/memdisk iso raw" in script
    assert "initrd http://10.0.0.1:8080/http/gparted-live-1.7.0.iso" in script
