from app.backend.ipxe_manager import iPXEEntry, iPXEGenerator, iPXEMenu


def test_grub_generator_snapshot():
    menu = iPXEMenu(
        title="GRUB Menu",
        timeout=60000,
        entries=[
            iPXEEntry(
                name="ubuntu",
                title="Ubuntu",
                kernel="ubuntu/vmlinuz",
                initrd="ubuntu/initrd",
                cmdline="ip=dhcp",
                entry_type="boot",
            ),
            iPXEEntry(
                name="rescue",
                title="Rescue",
                kernel="rescue/vmlinuz",
                initrd="rescue/initrd",
                cmdline="single",
                entry_type="boot",
            ),
        ],
    )

    grub = iPXEGenerator.generate_grub_config(menu)
    expected = """# GRUB Configuration
# Generated by PXE Boot Station

set timeout=60
set default=0

menuentry 'Rescue' {
    echo 'Loading Rescue...'
    linux rescue/vmlinuz single
    initrd rescue/initrd
}

menuentry 'Ubuntu' {
    echo 'Loading Ubuntu...'
    linux ubuntu/vmlinuz ip=dhcp
    initrd ubuntu/initrd
}
"""

    # Order in generator is by boot entries sequence; compare sets of lines ignoring blank lines
    def normalized(text: str):
        return [line.strip() for line in text.strip().splitlines() if line.strip()]

    assert normalized(grub) == normalized(expected)
